name: Update ligo version
on:
  schedule:
    # every hour on the 30 minute mark (github has a lot of jobs running every hour on the hour)
    - cron:  "30 */1 * * *"
jobs:
  update-version:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install runtime dependencies
        run: |
          brew install jq coreutils gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Update Formula
        run: ./scripts/update-formula.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'Formula'
          default_author: github_actions
          message: "Update to latest release"
          branch: master
