name: Update ligo version
on:
  # schedule:
  #   # Every Thursday at 00:30. The 30 minute mark is chosen because github has a lot of jobs running every hour on the hour
  #   - cron:  "30 0 * * Thu"
  push:
    branches: [master]
  pull_request:
jobs:
  update-version:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install runtime dependencies
        run: |
          brew install jq coreutils gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Update Formula
        run: ./scripts/update-formula.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.head_ref }}
          branch: auto/ligo-update-bottles
          commit-message: "Update ligo bottles"
          title: "Update ligo bottles with the latest release"
          delete-branch: true

