name: Update ligo version
on:
  schedule:
    # Update ligo every Thursday at 00:30 minute mark (github has a lot of jobs running every hour on the hour)
    - cron:  "30 0 * * Thu"
jobs:
  update-version:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install runtime dependencies
        run: |
          brew install jq coreutils gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

      - name: Update Formula
        run: ./scripts/update-formula.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add: 'Formula'
          default_author: github_actions
          message: "Update to latest release"
          branch: master
